language: android
dist: trusty

git:
  depth: 1

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.0
    - android-30

before_install:
  - sdkmanager --list

install:
  - yes | sdkmanager "ndk;21.0.6113669"
